freebsd_instance:
  image: freebsd-11-1-release-amd64

build_task:
  check_script:
    - whereis make
    - whereis gmake
    - whereis gcc
  install_script:
    ## gmake is necessary, otherwise bsd make is used and some cryptic "No operator" errors are shown
    - pkg install -y gmake
    - pkg install -y libiconv
    - pkg install -y gmp
    - pkg install -y postgresql95-client
    - pkg install -y pkgconf
    - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-freebsd-x86_64.tar.gz | tar zxf - -C /tmp
    - sudo mv /tmp/stack-1.7.1-freebsd-x86_64/stack /usr/bin
  test_script:
    - stack --version
  build_script:
    - stack build --verbose --install-ghc --copy-bins --local-bin-path .
  stack_cache:
    folder: "~/.stack"
    fingerprint_script:
      - cat stack.yaml
      - cat postgrest.cabal
  stack_work_cache:
    folder: ".stack-work"
    fingerprint_script:
      - cat stack.yaml
      - cat postgrest.cabal
