module Feature.OpenApi.RootSpec where

import Network.HTTP.Types

import Test.Hspec          hiding (pendingWith)
import Test.Hspec.Wai
import Test.Hspec.Wai.JSON

import PostgREST.Config                  (AppConfig (..))
import PostgREST.SchemaCache.Identifiers (QualifiedIdentifier (..))
import PostgREST.Version                 (prettyVersion)

import Protolude  hiding (get)
import SpecHelper

spec :: SpecWithConfig
spec withConfig = do
  withConfig (baseCfg { configDbRootSpec = Just $ QualifiedIdentifier mempty "root" }) $
    describe "root spec function" $ do
      it "accepts application/openapi+json" $ do
        request methodGet "/"
          [("Accept","application/openapi+json")] "" `shouldRespondWith`
          [json|{
             "swagger": "2.0",
             "info": {"title": "PostgREST API", "description": "This is a dynamic API generated by PostgREST"}
            }|]
          { matchHeaders = ["Content-Type" <:> "application/openapi+json; charset=utf-8"] }

      it "accepts application/json" $ do
        request methodGet "/"
          [("Accept","application/json")] "" `shouldRespondWith`
          [json|{
             "swagger": "2.0",
             "info": {"title": "PostgREST API", "description": "This is a dynamic API generated by PostgREST"}
            }|]
          { matchHeaders = ["Content-Type" <:> "application/json; charset=utf-8"] }

  withConfig (baseCfg { configDbRootSpec = Just $ QualifiedIdentifier mempty "root_int" }) $
    describe "root spec function with an invalid parameter" $ do
      it "is not recognized" $
        request methodGet "/"
          [("Accept","application/openapi+json")] "" `shouldRespondWith` 404

  withConfig (baseCfg
    { configDbRootSpec = Just $ QualifiedIdentifier mempty "root_with_json"
    , configDbSchemas = "test" :| ["v1"]
    , configOpenApiServerProxyUri = Just "https://example.com/base"
    }) $
    describe "root spec function with json parameter" $ do
      it "accepts application/openapi+json" $ do
        request methodGet "/"
          [("Accept","application/openapi+json")] "" `shouldRespondWith`
          [json|{
             "swagger": "2.0",
             "info": {"title": "PostgREST API", "description": "This is a dynamic API generated by PostgREST"},
             "server-host": "localhost",
             "server-port": "3000",
             "openapi-server-proxy-uri": "https://example.com/base",
             "db-schemas": ["test", "v1"],
             "version": #{decodeUtf8 prettyVersion}
            }|]
          { matchHeaders = ["Content-Type" <:> "application/openapi+json; charset=utf-8"] }

      it "accepts application/json" $ do
        request methodGet "/"
          [("Accept","application/json")] "" `shouldRespondWith`
          [json|{
             "swagger": "2.0",
             "info": {"title": "PostgREST API", "description": "This is a dynamic API generated by PostgREST"},
             "server-host": "localhost",
             "server-port": "3000",
             "openapi-server-proxy-uri": "https://example.com/base",
             "db-schemas": ["test", "v1"],
             "version": #{decodeUtf8 prettyVersion}
            }|]
          { matchHeaders = ["Content-Type" <:> "application/json; charset=utf-8"] }
